### ISSUE TITLE
Got Expert actions all being equal in the self-collected dataset

### ISSUE THREAD

**Issue by gmzguo** [dunnolab/xland-minigrid-datasets#4]
When I collected trivial dataset myself, all the expert actions in one learning history are the same, which is obviously not correct. 
<img width="1033" alt="Screenshot 2024-10-23 at 3 10 12 PM" src="https://github.com/user-attachments/assets/8e314825-4fca-4ba6-aa1c-6ac2970c3222">

**Comment by Howuhh** [comment]
Hi @gmzguo! It's a little weird. Can you show the expert learning curve? Are you sure he's converged to good return?

**Comment by Howuhh** [comment]
Double checked the existing datasets and they are fine, all possible actions present in expert actions:

<img width="457" alt="Screenshot 2024-10-24 at 13 38 49" src="https://github.com/user-attachments/assets/d67a55a9-6e14-46b6-90d6-59a62a4b0191">

**Comment by gmzguo** [comment]
Thank you. I found out the reason. It turned out I am not training long enough.
